site_name: "BeTFSM documentation"
site_author: "Erwin Aertbelien"
repo_url: "https://github.com/Robotics-Research-Group-KUL/betfsm"
edit_uri: edit/main/documentation/docs
copyright: "LGPL-3.0-only"
theme:
  name: "readthedocs"




nav:
  - "Documentation":
    - "Home": 'index.md'
    - "Tutorials":
      - "My first BETFSM tree" : "tutorial_sequence1.md"
      - "Up & Down": "upanddown.md"
      - "Action servers": "actionserver_ex.md" 
    - "BeTFSM":
      - "TickingState" : "tickingstate.md"
      - "TickingStateMachine" : "tickingstatemachine.md"
      - "Visitor" : "visitor.md"
      - "Generator" : "generator.md"
      - "Sequence" : "sequence.md"
      - "ConcurrentSequence" : "concurrentsequence.md"
      - "Fallback" : "fallback.md"
      - "ConcurrentFallback" : "concurrentfallback.md"
      - "Concurrent" : "concurrent.md"
      - "WaitFor" : 'waitfor.md'
      - "WaitForever" : 'waitforever.md'
      - "TimedWait" : 'timedwait.md'
      - "TimedRepeat" : "timedrepeat.md"
      - "While" : 'while.md'
      - "Repeat" : 'repeat.md'        
      - "Message" : "message.md"
      - "LogBlackboard" : 'logblackboard.md'
      - "Compute" : "compute.md"
      - "Adapt" : "adapt.md"
      - "BeTFSMRunner": "betfsmrunner.md"
#    - "BeTFSM ROS2":  
#      - "ServiceClient" : 'serviceclient.md'
#      - "LifeCycle" : 'lifecycle.md'
#      - "TimedRepeat for ROS2" : timedrepeat_ros2.md
#      - "TimedWait for ROS2" : 'rostimedwait_ros2.md'
#      - "Timeout" : "timeout.md"
#    - "BeTFSM eTaSL": 'etaslstatemachine.md'
##    - "Action server": "actionserver.md"
    - "Utilities" : 'utils.md'
    - "About": 'about.md'



plugins:
  - search
  - codeinclude:
      title_mode: none
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          paths: [../betfsm, ../betfsm_demos, ../betfsm_ros, ../betfsm_crospi,..]
          options: 
            show_source: false
            show_root_heading: true 
            docstring_style: google
     
extra_css:
- css/mkdocstrings.css

markdown_extensions:
    - mkdocs_graphviz
    - admonition
    - pymdownx.details
    # - pymdownx.highlight:
    #     anchor_linenums: true
    #     line_spans: __span
    #     use_pygments: true
    # - pymdownx.snippets
    - pymdownx.details
    - pymdownx.arithmatex:
        generic: true




extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML

#  - javascripts/mathjaxhelper.js
