site_name: "Yasmin_eTaSL documenttaion"
site_author: "Erwin Aertbelien"
repo_url: "https://gitlab.kuleuven.be/rob-expressiongraphs/ros2/yasmin_etasl"
copyright: "LGPL-3.0-only"
theme:
  name: "readthedocs"




nav:
  - "Documentation":
    - "Home": 'index.md'
    - "Yasmin":
      - "Tickingstates":
        - "TickingState" : "tickingstate.md"
        - "Generator" : "generator.md"
        - "Sequence" : "sequence.md"
        - "ConcurrentSequence" : "concurrentsequence.md"
        - "Fallback" : "fallback.md"
        - "ConcurrentFallback" : "concurrentfallback.md"
        - "WaitFor" : 'waitfor.md'
        - "WaitForever" : 'waitforever.md'
        - "ConditionWhile" : 'conditionwhile.md'
        - "Repeat" : 'repeat.md'        
      - "TickingStateMachine": 'tickingstatemachine.md'
      - "ROS 2":  
        - "ServiceClient" : 'serviceclient.md'
        - "LifeCycle" : 'lifecycle.md'
        - "TopicState" : 'topicstate.md'
        - "TimedRepeat" : timedrepeat.md
        - "TimedWait" : 'timedwait.md'
        - "Timeout" : "timeout.md"
      - "eTaSL":
        - "eTaSL_StateMachine": 'etaslstatemachine.md'
    - "Utilities" : 'utils.md'
    - "About": 'about.md'
    - "Todo list" : "TODO.md"



plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        options:
          show_source: false
          show_root_heading: true 
          docstring_style: google
   
extra_css:
- css/mkdocstrings.css

markdown_extensions:
    - mkdocs_graphviz

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
