name: Humble Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"
  release:
    types: [created, published]

jobs:
  humble_build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest 
    steps:
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: betfsm betfsm_interfaces
          target-ros2-distro: humble
          skip-tests: true
          coverage-result: false
